# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:

- script: |
    export TEMPLATECONF=meta-intel/meta-s2600wf
    source oe-init-build-env
    bitbake obmc-phosphor-image
  displayName: 'Build'
